[package]
name = "buzz"
version = "1.0.6"

description = "A simple system tray application for notifying about unseen e-mail"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>",
           "rhn <gihu.rhn@porcupinefactory.org>"]

homepage = "https://github.com/jonhoo/buzz"
repository = "https://github.com/jonhoo/buzz.git"

keywords = ["email","cli","systray","notification"]
categories = ["command-line-utilities", "email"]

license = "MIT/Apache-2.0"

[profile.release]
debug=true

[dependencies]
imap = "0.6.0"
native-tls = "0.1"
systray = "0.2.0"
mailparse = "0.5.1"
toml = "0.4.2"
xdg = "2.1.0"
notify-rust = "3.4.0"
rayon = "0.8.2"
openssl = "0.9"
